### ISSUE TITLE
Inefficiences

### ISSUE THREAD

**Issue by drahnr** [ijagberg/influx#1]
Thank you for providing the impl 

Commonly the performance impact of a metrics collector should be small. I've dug through the code and saw a few instances that made me wary of using the library, in particular https://github.com/ijagberg/influx/blob/main/src/lib.rs#L149-L150

I am not entirely sure why the hashmap is required, since there is never a lookup? It causes two re-collections and given the assumption the number of tags and fields is small compared to todays cachelines, it seems rather unfortunate to not stick with slices.

Did you check the impact on a real world codebase that's CPU bound? I am considering using it at for a larger project.

Thanks!

**Comment by ijagberg** [comment]
Hey, thanks for showing some interest in this :)

I'm sure there are tons of inefficiencies, I made this library for my own projects and thought I might as well publish it in case someone else wants to use it. 

Good point about the HashMaps, you're probably correct that they aren't necessary. I haven't done any real benchmarking. I'm not sure I understand exactly what you mean with using slices though, a slice of tuples [(tagname, tagvalue)] and [(fieldname, fieldvalue)] would still need to be heap-allocated, no?
