### ISSUE TITLE
what to do about special charaters in field values?

### ISSUE THREAD

**Issue by alsuren** [ijagberg/influx#4]
I am currently collecting user agent information over at https://github.com/cargo-bins/cargo-quickinstall/pull/165#pullrequestreview-2288501266 and I managed to end up with some a fun Tag Key of `like Gecko) Chrome/70.0.3538.67 Safari/537.36,version` (see screenshot from the latest influxdb cloud).

![Screenshot 2024-09-08 at 12 06 54](https://github.com/user-attachments/assets/ba5d3539-75cd-49d2-9d16-718ab07e0a12)

I'm assuming something is not being escaped correctly somewhere? I'm still digging into it.

https://docs.influxdata.com/influxdb/v1/write_protocols/line_protocol_tutorial/#special-characters-and-keywords says to use \ for escaping everything. It seems like most other user agent strings are correctly reported, so I'm going to try writing a unit test for this and see where the problem is.

**Comment by NobodyXu** [comment]
Maybe it's too long that it doesn't show the full string?

Or is it truncated somewhere?

**Comment by alsuren** [comment]
~I think the problem is more likely to be on our end. Sorry for the spam. Will re-open if it's a library problem once I've narrowed it down.~

**Comment by ijagberg** [comment]
I have published version 2.1.0, which includes the changes in #5
